# Generated by Django 5.2.1 on 2025-06-10 11:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=models.CharField(max_length=200), unique=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Creative / Digital', 'Creative / Digital'), ('Administrative', 'Administrative'), ('Retail', 'Retail'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Fulltime'), ('partime', 'Partime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
