# Generated by Django 5.2.1 on 2025-06-15 03:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobsmodel_slug_alter_jobsmodel_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Customer Service', 'Customer Service'), ('Marketing', 'Marketing'), ('Creative / Digital', 'Creative / Digital'), ('Retail', 'Retail'), ('Administrative', 'Administrative'), ('Operations', 'Operations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('on-site', 'On-site'), ('remote', 'Remote')], max_length=50),
        ),
    ]
