# Generated by Django 5.2.1 on 2025-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobsmodel_categories_alter_jobsmodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Creative / Digital', 'Creative / Digital'), ('Marketing', 'Marketing'), ('Retail', 'Retail'), ('Administrative', 'Administrative'), ('Operations', 'Operations'), ('Customer Service', 'Customer Service')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
