# Generated by Django 5.2.1 on 2025-06-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobsmodel_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Administrative', 'Administrative'), ('Operations', 'Operations'), ('Customer Service', 'Customer Service'), ('Retail', 'Retail'), ('Creative / Digital', 'Creative / Digital')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('on-site', 'On-site'), ('remote', 'Remote')], max_length=50),
        ),
    ]
