# Generated by Django 5.2.1 on 2025-06-19 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobsmodel_categories_alter_jobsmodel_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='saved',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Creative / Digital', 'Creative / Digital'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Retail', 'Retail'), ('Operations', 'Operations'), ('Administrative', 'Administrative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('on-site', 'On-site')], max_length=50),
        ),
    ]
