# Generated by Django 5.2.1 on 2025-06-23 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobsmodel_saved_alter_jobsmodel_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Customer Service', 'Customer Service'), ('Operations', 'Operations'), ('Administrative', 'Administrative'), ('Retail', 'Retail'), ('Marketing', 'Marketing'), ('Creative / Digital', 'Creative / Digital')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
