# Generated by Django 5.2.1 on 2025-07-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobsmodel_categories_alter_jobsmodel_saved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Administrative', 'Administrative'), ('Customer Service', 'Customer Service'), ('Operations', 'Operations'), ('Retail', 'Retail'), ('Creative / Digital', 'Creative / Digital'), ('Marketing', 'Marketing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('on-site', 'On-site'), ('remote', 'Remote')], max_length=50),
        ),
    ]
