# Generated by Django 5.2.1 on 2025-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobsmodel_categories_alter_jobsmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Retail', 'Retail'), ('Creative / Digital', 'Creative / Digital'), ('Administrative', 'Administrative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Fulltime'), ('partime', 'Partime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
