# Generated by Django 5.2.1 on 2025-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobsmodel_categories_alter_jobsmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Operations', 'Operations'), ('Administrative', 'Administrative'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Creative / Digital', 'Creative / Digital')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='job_type',
            field=models.CharField(choices=[('partime', 'Partime'), ('fulltime', 'Fulltime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
