# Generated by Django 5.2.1 on 2025-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobsmodel_categories_alter_jobsmodel_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='job_link',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='categories',
            field=models.CharField(choices=[('Creative / Digital', 'Creative / Digital'), ('Customer Service', 'Customer Service'), ('Administrative', 'Administrative'), ('Marketing', 'Marketing'), ('Retail', 'Retail'), ('Operations', 'Operations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='work_location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On-site'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
